/*
Routes starting with a + have special significance to Expo Router,
and are used for specific purposes. One example is +not-found, which
catches any requests that don't match a route in your app.
+html is used to customize the HTML boilerplate used by your app on web.
+native-intent is used to handle deep links into your app that don't match
a specific route, such as links generated by third party services.
*/

import { Link, Stack } from 'expo-router';
import { View, StyleSheet } from 'react-native';

export default function NotFoundScreen() {
  return (
    <>
      <Stack.Screen options={{ title: "Oops! This screen doesn't exist." }} />
      <View style={styles.container}>
        <Link href="/">Go to home screen</Link>
      </View>
    </>
  );
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
